import json
from copy import deepcopy
from pprint import pprint


def get_data_info(data_input: list):
    headers = dict()
    for row in data_input:
        for key in row:
            if key not in headers:
                headers[key] = {row[key]}
            elif key in headers:
                headers[key].add(row[key])
    # Get header types
    headers_type = dict((head, set(type(entry) for entry in headers[head])) for head in headers)
    # Get all possible types variants
    type_set = set(tuple(headers_type[types]) for types in headers_type)
    # Calculate null size for all columns
    headers_null_size = dict()
    for head in headers:
        counter = 0
        for line in data_input:
            if head not in line:
                counter += 1
        headers_null_size[head] = counter
        pass
    return {'headers': headers, 'headers_type': headers_type, 'type_set': type_set,
            'headers_null_size': headers_null_size}


# Load data
with open('/home/windr/CS593_Data/all_data.json', 'r') as fh:
    data = json.load(fh)

# Remove rows without Y response
data = list(line for line in data if 'MD_EARN_WNE_P10' in line)
# Get header information
di = get_data_info(data)

# Drop columns with more than 30% of null values
thresh = len(data) * 0.30
for i in range(len(data)):
    temp = list()
    for header in data[i]:
        if di['headers_null_size'][header] >= thresh:
            temp.append(header)
    for hd in temp:
        data[i].pop(hd, None)
# Get header information
di = get_data_info(data)

# Create copy of original cleaned data
cleaned_data = deepcopy(data)
cdi = get_data_info(cleaned_data)

# Define manual drop column lists
mdrop1 = ['ACCREDAGENCY', 'INSTURL', 'NPCURL', 'HCM2', 'LOCALE', 'LOCALE2', 'LATITUDE', 'LONGITUDE',
          'CCBASIC', 'CCUGPROF', 'CCSIZSET', 'HBCU', 'PBI', 'ANNHI', 'TRIBAL', 'AANAPII', 'HSI',
          'NANTI', 'MENONLY', 'WOMENONLY', 'RELAFFIL', 'UG', 'UGDS_WHITENH', 'UGDS_BLACKNH', 'UGDS_API',
          'UGDS_AIANOLD', 'UGDS_HISPOLD', 'UG_NRA', 'UG_UNKN', 'UG_WHITENH', 'UG_BLACKNH', 'UG_API',
          'UG_AIANOLD', 'UG_HISPOLD', 'PPTUG_EF2', 'CURROPER', 'NPT4_PROG', 'NPT4_OTHER', 'NPT41_PROG',
          'NPT42_PROG', 'NPT43_PROG', 'NPT44_PROG', 'NPT45_PROG', 'NPT41_OTHER', 'NPT42_OTHER',
          'NPT43_OTHER', 'NPT44_OTHER', 'NPT45_OTHER', 'NPT4_048_PROG', 'NPT4_048_OTHER', 'NPT4_3075_PROG',
          'NPT4_3075_OTHER', 'NPT4_75UP_PROG', 'NPT4_75UP_OTHER', 'NUM4_PROG', 'NUM4_OTHER', 'NUM41_PROG',
          'NUM42_PROG', 'NUM43_PROG', 'NUM44_PROG', 'NUM45_PROG', 'NUM41_OTHER', 'NUM42_OTHER',
          'NUM43_OTHER', 'NUM44_OTHER', 'NUM45_OTHER', 'C150_4_POOLED', 'C150_L4_POOLED', 'POOLYRS',
          'D150_4_POOLED', 'D150_L4_POOLED', 'C150_4_WHITENH', 'C150_4_BLACKNH', 'C150_4_API',
          'C150_4_AIANOLD', 'C150_4_HISPOLD', 'C150_L4_WHITENH', 'C150_L4_BLACKNH', 'C150_L4_API',
          'C150_L4_AIANOLD', 'C150_L4_HISPOLD', 'C200_4_POOLED', 'C200_L4_POOLED', 'POOLYRS200',
          'D200_4_POOLED', 'D200_L4_POOLED', 'UG25ABV', 'CDR2', 'GRAD_DEBT_MDN10YR', 'COUNT_ED',
          'AGE_ENTRY_SQ', 'AGEGE24', 'LNFAMINC', 'LNFAMINC_IND', 'PCT_WHITE', 'PCT_BLACK', 'PCT_ASIAN',
          'PCT_HISPANIC', 'PCT_BA', 'PCT_GRAD_PROF', 'PCT_BORN_US', 'MEDIAN_HH_INC', 'POVERTY_RATE',
          'UNEMP_RATE', 'LN_MEDIAN_HH_INC', 'FSEND_COUNT', 'FSEND_1', 'FSEND_2', 'FSEND_3', 'FSEND_4',
          'FSEND_5', 'PCT10_EARN_WNE_P10', 'PCT90_EARN_WNE_P10', 'COUNT_WNE_INDEP0_INC1_P10',
          'GT_25K_P10', 'MN_EARN_WNE_INDEP0_INC1_P10', 'PCT10_EARN_WNE_P6', 'PCT90_EARN_WNE_P6',
          'COUNT_WNE_INDEP0_INC1_P6', 'GT_25K_P6', 'MN_EARN_WNE_INDEP0_INC1_P6', 'COUNT_NWNE_P7',
          'COUNT_WNE_P7', 'MN_EARN_WNE_P7', 'SD_EARN_WNE_P7', 'GT_25K_P7', 'PCT10_EARN_WNE_P8',
          'PCT90_EARN_WNE_P8', 'GT_25K_P8', 'COUNT_NWNE_P9', 'COUNT_WNE_P9', 'MN_EARN_WNE_P9',
          'SD_EARN_WNE_P9', 'GT_25K_P9', 'GRAD_DEBT_MDN10YR_SUPP', 'C150_L4_POOLED_SUPP',
          'C150_4_POOLED_SUPP', 'C200_L4_POOLED_SUPP', 'C200_4_POOLED_SUPP', 'CDR2_DENOM',
          'T4APPROVALDATE', 'D150_4_WHITENH', 'D150_4_BLACKNH', 'D150_4_API', 'D150_4_AIANOLD',
          'D150_4_HISPOLD', 'D150_L4_WHITENH', 'D150_L4_BLACKNH', 'D150_L4_API', 'D150_L4_AIANOLD',
          'D150_L4_HISPOLD', 'ACCREDCODE', 'OMACHT6_FTFT', 'OMAWDP6_FTFT', 'OMACHT8_FTFT',
          'OMAWDP8_FTFT', 'OMENRYP8_FTFT', 'OMENRAP8_FTFT', 'OMENRUP8_FTFT', 'OMACHT6_PTFT',
          'OMAWDP6_PTFT', 'OMACHT8_PTFT', 'OMAWDP8_PTFT', 'OMENRYP8_PTFT', 'OMENRAP8_PTFT',
          'OMENRUP8_PTFT', 'OMACHT6_FTNFT', 'OMAWDP6_FTNFT', 'OMACHT8_FTNFT', 'OMAWDP8_FTNFT',
          'OMENRYP8_FTNFT', 'OMENRAP8_FTNFT', 'OMENRUP8_FTNFT', 'OMACHT6_PTNFT', 'OMAWDP6_PTNFT',
          'OMACHT8_PTNFT', 'OMAWDP8_PTNFT', 'OMENRYP8_PTNFT', 'OMENRAP8_PTNFT', 'OMENRUP8_PTNFT',
          'RET_FT4_POOLED', 'RET_FTL4_POOLED', 'RET_PT4_POOLED', 'RET_PTL4_POOLED', 'RET_FT_DEN4_POOLED',
          'RET_FT_DENL4_POOLED', 'RET_PT_DEN4_POOLED', 'RET_PT_DENL4_POOLED', 'POOLYRSRET_FT',
          'POOLYRSRET_PT', 'RET_FT4_POOLED_SUPP', 'RET_FTL4_POOLED_SUPP', 'RET_PT4_POOLED_SUPP',
          'RET_PTL4_POOLED_SUPP', 'TRANS_4_POOLED', 'TRANS_L4_POOLED', 'DTRANS_4_POOLED',
          'DTRANS_L4_POOLED', 'TRANS_4_POOLED_SUPP', 'TRANS_L4_POOLED_SUPP', 'C100_4_POOLED',
          'C100_L4_POOLED', 'D100_4_POOLED', 'D100_L4_POOLED', 'POOLYRS100', 'C100_4_POOLED_SUPP',
          'C100_L4_POOLED_SUPP', 'C150_4_PELL', 'D150_4_PELL', 'C150_L4_PELL', 'D150_L4_PELL',
          'C150_4_LOANNOPELL', 'D150_4_LOANNOPELL', 'C150_L4_LOANNOPELL', 'D150_L4_LOANNOPELL',
          'C150_4_NOLOANNOPELL', 'D150_4_NOLOANNOPELL', 'C150_L4_NOLOANNOPELL', 'D150_L4_NOLOANNOPELL',
          'OMACHT6_FTFT_POOLED', 'OMAWDP6_FTFT_POOLED', 'OMACHT8_FTFT_POOLED', 'OMAWDP8_FTFT_POOLED',
          'OMENRYP8_FTFT_POOLED', 'OMENRAP8_FTFT_POOLED', 'OMENRUP8_FTFT_POOLED', 'OMACHT6_PTFT_POOLED',
          'OMAWDP6_PTFT_POOLED', 'OMACHT8_PTFT_POOLED', 'OMAWDP8_PTFT_POOLED', 'OMENRYP8_PTFT_POOLED',
          'OMENRAP8_PTFT_POOLED', 'OMENRUP8_PTFT_POOLED', 'OMACHT6_FTNFT_POOLED', 'OMAWDP6_FTNFT_POOLED',
          'OMACHT8_FTNFT_POOLED', 'OMAWDP8_FTNFT_POOLED', 'OMENRYP8_FTNFT_POOLED',
          'OMENRAP8_FTNFT_POOLED', 'OMENRUP8_FTNFT_POOLED', 'OMACHT6_PTNFT_POOLED',
          'OMAWDP6_PTNFT_POOLED', 'OMACHT8_PTNFT_POOLED', 'OMAWDP8_PTNFT_POOLED', 'OMENRYP8_PTNFT_POOLED',
          'OMENRAP8_PTNFT_POOLED', 'OMENRUP8_PTNFT_POOLED', 'poolyrsOM_FTFT', 'poolyrsOM_PTFT',
          'poolyrsOM_FTNFT', 'poolyrsOM_PTNFT', 'OMAWDP6_FTFT_POOLED_SUPP', 'OMAWDP8_FTFT_POOLED_SUPP',
          'OMENRYP8_FTFT_POOLED_SUPP', 'OMENRAP8_FTFT_POOLED_SUPP', 'OMENRUP8_FTFT_POOLED_SUPP',
          'OMAWDP6_PTFT_POOLED_SUPP', 'OMAWDP8_PTFT_POOLED_SUPP', 'OMENRYP8_PTFT_POOLED_SUPP',
          'OMENRAP8_PTFT_POOLED_SUPP', 'OMENRUP8_PTFT_POOLED_SUPP', 'OMAWDP6_FTNFT_POOLED_SUPP',
          'OMAWDP8_FTNFT_POOLED_SUPP', 'OMENRYP8_FTNFT_POOLED_SUPP', 'OMENRAP8_FTNFT_POOLED_SUPP',
          'OMENRUP8_FTNFT_POOLED_SUPP', 'OMAWDP6_PTNFT_POOLED_SUPP', 'OMAWDP8_PTNFT_POOLED_SUPP',
          'OMENRYP8_PTNFT_POOLED_SUPP', 'OMENRAP8_PTNFT_POOLED_SUPP', 'OMENRUP8_PTNFT_POOLED_SUPP']  # Why?

mdrop2 = ['COUNT_NWNE_P10',  'COUNT_WNE_P10',  'MN_EARN_WNE_P10',  'PCT10_EARN_WNE_P10',
          'PCT25_EARN_WNE_P10',  'PCT75_EARN_WNE_P10',  'PCT90_EARN_WNE_P10',  'SD_EARN_WNE_P10',
          'COUNT_WNE_INC1_P10',  'COUNT_WNE_INC2_P10',  'COUNT_WNE_INC3_P10',
          'COUNT_WNE_INDEP0_INC1_P10',  'COUNT_WNE_INDEP0_P10',  'COUNT_WNE_INDEP1_P10',
          'COUNT_WNE_MALE0_P10',  'COUNT_WNE_MALE1_P10',  'GT_25K_P10',  'GT_28K_P10',
          'MN_EARN_WNE_INC1_P10',  'MN_EARN_WNE_INC2_P10',  'MN_EARN_WNE_INC3_P10',
          'MN_EARN_WNE_INDEP0_INC1_P10',  'MN_EARN_WNE_INDEP0_P10',  'MN_EARN_WNE_INDEP1_P10',
          'MN_EARN_WNE_MALE0_P10',  'MN_EARN_WNE_MALE1_P10']  # Columns related to Y response

mdrop3 = ['STABBR',  'ZIP',  'ACCREDAGENCY',  'INSTURL',  'NPCURL',  'REPAY_DT_MDN',  'SEPAR_DT_MDN',
          'ALIAS',  'ACCREDCODE',  'T4APPROVALDATE']  # String fields

# Drop keys from manual drop lists
for i in range(len(cleaned_data)):
    for key in list(cleaned_data[i].keys()):
        if key in mdrop1 + mdrop2 + mdrop3:
            cleaned_data[i].pop(key)
cdi = get_data_info(cleaned_data)

# Drop keys that are not in numerical list
numerical = ['NUMBRANCH', 'TUITFTE', 'INEXPFTE', 'DEATH_YR2_RT', 'COMP_ORIG_YR2_RT', 'COMP_4YR_TRANS_YR2_RT', 'COMP_2YR_TRANS_YR2_RT', 'WDRAW_ORIG_YR2_RT', 'WDRAW_4YR_TRANS_YR2_RT', 'WDRAW_2YR_TRANS_YR2_RT', 'ENRL_ORIG_YR2_RT', 'ENRL_4YR_TRANS_YR2_RT', 'ENRL_2YR_TRANS_YR2_RT', 'UNKN_ORIG_YR2_RT', 'UNKN_4YR_TRANS_YR2_RT', 'UNKN_2YR_TRANS_YR2_RT', 'LO_INC_DEATH_YR2_RT', 'LO_INC_COMP_ORIG_YR2_RT', 'LO_INC_COMP_4YR_TRANS_YR2_RT', 'LO_INC_COMP_2YR_TRANS_YR2_RT', 'LO_INC_WDRAW_ORIG_YR2_RT', 'LO_INC_WDRAW_4YR_TRANS_YR2_RT', 'LO_INC_WDRAW_2YR_TRANS_YR2_RT', 'LO_INC_ENRL_ORIG_YR2_RT', 'LO_INC_ENRL_4YR_TRANS_YR2_RT', 'LO_INC_ENRL_2YR_TRANS_YR2_RT', 'LO_INC_UNKN_ORIG_YR2_RT', 'LO_INC_UNKN_4YR_TRANS_YR2_RT', 'LO_INC_UNKN_2YR_TRANS_YR2_RT', 'MD_INC_DEATH_YR2_RT', 'MD_INC_COMP_ORIG_YR2_RT', 'MD_INC_COMP_4YR_TRANS_YR2_RT', 'MD_INC_COMP_2YR_TRANS_YR2_RT', 'MD_INC_WDRAW_ORIG_YR2_RT', 'MD_INC_WDRAW_4YR_TRANS_YR2_RT', 'MD_INC_WDRAW_2YR_TRANS_YR2_RT', 'MD_INC_ENRL_ORIG_YR2_RT', 'MD_INC_ENRL_4YR_TRANS_YR2_RT', 'MD_INC_ENRL_2YR_TRANS_YR2_RT', 'MD_INC_UNKN_ORIG_YR2_RT', 'MD_INC_UNKN_4YR_TRANS_YR2_RT', 'MD_INC_UNKN_2YR_TRANS_YR2_RT', 'HI_INC_DEATH_YR2_RT', 'HI_INC_COMP_ORIG_YR2_RT', 'HI_INC_COMP_4YR_TRANS_YR2_RT', 'HI_INC_COMP_2YR_TRANS_YR2_RT', 'HI_INC_WDRAW_ORIG_YR2_RT', 'HI_INC_WDRAW_4YR_TRANS_YR2_RT', 'HI_INC_WDRAW_2YR_TRANS_YR2_RT', 'HI_INC_ENRL_ORIG_YR2_RT', 'HI_INC_ENRL_4YR_TRANS_YR2_RT', 'HI_INC_ENRL_2YR_TRANS_YR2_RT', 'HI_INC_UNKN_ORIG_YR2_RT', 'HI_INC_UNKN_4YR_TRANS_YR2_RT', 'HI_INC_UNKN_2YR_TRANS_YR2_RT', 'DEP_DEATH_YR2_RT', 'DEP_COMP_ORIG_YR2_RT', 'DEP_COMP_4YR_TRANS_YR2_RT', 'DEP_COMP_2YR_TRANS_YR2_RT', 'DEP_WDRAW_ORIG_YR2_RT', 'DEP_WDRAW_4YR_TRANS_YR2_RT', 'DEP_WDRAW_2YR_TRANS_YR2_RT', 'DEP_ENRL_ORIG_YR2_RT', 'DEP_ENRL_4YR_TRANS_YR2_RT', 'DEP_ENRL_2YR_TRANS_YR2_RT', 'DEP_UNKN_ORIG_YR2_RT', 'DEP_UNKN_4YR_TRANS_YR2_RT', 'DEP_UNKN_2YR_TRANS_YR2_RT', 'IND_DEATH_YR2_RT', 'IND_COMP_ORIG_YR2_RT', 'IND_COMP_4YR_TRANS_YR2_RT', 'IND_COMP_2YR_TRANS_YR2_RT', 'IND_WDRAW_ORIG_YR2_RT', 'IND_WDRAW_4YR_TRANS_YR2_RT', 'IND_WDRAW_2YR_TRANS_YR2_RT', 'IND_ENRL_ORIG_YR2_RT', 'IND_ENRL_4YR_TRANS_YR2_RT', 'IND_ENRL_2YR_TRANS_YR2_RT', 'IND_UNKN_ORIG_YR2_RT', 'IND_UNKN_4YR_TRANS_YR2_RT', 'IND_UNKN_2YR_TRANS_YR2_RT', 'FEMALE_DEATH_YR2_RT', 'FEMALE_COMP_ORIG_YR2_RT', 'FEMALE_COMP_4YR_TRANS_YR2_RT', 'FEMALE_COMP_2YR_TRANS_YR2_RT', 'FEMALE_WDRAW_ORIG_YR2_RT', 'FEMALE_WDRAW_4YR_TRANS_YR2_RT', 'FEMALE_WDRAW_2YR_TRANS_YR2_RT', 'FEMALE_ENRL_ORIG_YR2_RT', 'FEMALE_ENRL_4YR_TRANS_YR2_RT', 'FEMALE_ENRL_2YR_TRANS_YR2_RT', 'FEMALE_UNKN_ORIG_YR2_RT', 'FEMALE_UNKN_4YR_TRANS_YR2_RT', 'FEMALE_UNKN_2YR_TRANS_YR2_RT', 'MALE_DEATH_YR2_RT', 'MALE_COMP_ORIG_YR2_RT', 'MALE_COMP_4YR_TRANS_YR2_RT', 'MALE_COMP_2YR_TRANS_YR2_RT', 'MALE_WDRAW_ORIG_YR2_RT', 'MALE_WDRAW_4YR_TRANS_YR2_RT', 'MALE_WDRAW_2YR_TRANS_YR2_RT', 'MALE_ENRL_ORIG_YR2_RT', 'MALE_ENRL_4YR_TRANS_YR2_RT', 'MALE_ENRL_2YR_TRANS_YR2_RT', 'MALE_UNKN_ORIG_YR2_RT', 'MALE_UNKN_4YR_TRANS_YR2_RT', 'MALE_UNKN_2YR_TRANS_YR2_RT', 'PELL_DEATH_YR2_RT', 'PELL_COMP_ORIG_YR2_RT', 'PELL_COMP_4YR_TRANS_YR2_RT', 'PELL_COMP_2YR_TRANS_YR2_RT', 'PELL_WDRAW_ORIG_YR2_RT', 'PELL_WDRAW_4YR_TRANS_YR2_RT', 'PELL_WDRAW_2YR_TRANS_YR2_RT', 'PELL_ENRL_ORIG_YR2_RT', 'PELL_ENRL_4YR_TRANS_YR2_RT', 'PELL_ENRL_2YR_TRANS_YR2_RT', 'PELL_UNKN_ORIG_YR2_RT', 'PELL_UNKN_4YR_TRANS_YR2_RT', 'PELL_UNKN_2YR_TRANS_YR2_RT', 'NOPELL_DEATH_YR2_RT', 'NOPELL_COMP_ORIG_YR2_RT', 'NOPELL_COMP_4YR_TRANS_YR2_RT', 'NOPELL_COMP_2YR_TRANS_YR2_RT', 'NOPELL_WDRAW_ORIG_YR2_RT', 'NOPELL_WDRAW_4YR_TRANS_YR2_RT', 'NOPELL_WDRAW_2YR_TRANS_YR2_RT', 'NOPELL_ENRL_ORIG_YR2_RT', 'NOPELL_ENRL_4YR_TRANS_YR2_RT', 'NOPELL_ENRL_2YR_TRANS_YR2_RT', 'NOPELL_UNKN_ORIG_YR2_RT', 'NOPELL_UNKN_4YR_TRANS_YR2_RT', 'NOPELL_UNKN_2YR_TRANS_YR2_RT', 'LOAN_DEATH_YR2_RT', 'LOAN_COMP_ORIG_YR2_RT', 'LOAN_COMP_4YR_TRANS_YR2_RT', 'LOAN_COMP_2YR_TRANS_YR2_RT', 'LOAN_WDRAW_ORIG_YR2_RT', 'LOAN_WDRAW_4YR_TRANS_YR2_RT', 'LOAN_WDRAW_2YR_TRANS_YR2_RT', 'LOAN_ENRL_ORIG_YR2_RT', 'LOAN_ENRL_4YR_TRANS_YR2_RT', 'LOAN_ENRL_2YR_TRANS_YR2_RT', 'LOAN_UNKN_ORIG_YR2_RT', 'LOAN_UNKN_4YR_TRANS_YR2_RT', 'LOAN_UNKN_2YR_TRANS_YR2_RT', 'NOLOAN_DEATH_YR2_RT', 'NOLOAN_COMP_ORIG_YR2_RT', 'NOLOAN_COMP_4YR_TRANS_YR2_RT', 'NOLOAN_COMP_2YR_TRANS_YR2_RT', 'NOLOAN_WDRAW_ORIG_YR2_RT', 'NOLOAN_WDRAW_4YR_TRANS_YR2_RT', 'NOLOAN_WDRAW_2YR_TRANS_YR2_RT', 'NOLOAN_ENRL_ORIG_YR2_RT', 'NOLOAN_ENRL_4YR_TRANS_YR2_RT', 'NOLOAN_ENRL_2YR_TRANS_YR2_RT', 'NOLOAN_UNKN_ORIG_YR2_RT', 'NOLOAN_UNKN_4YR_TRANS_YR2_RT', 'NOLOAN_UNKN_2YR_TRANS_YR2_RT', 'FIRSTGEN_DEATH_YR2_RT', 'FIRSTGEN_COMP_ORIG_YR2_RT', 'FIRSTGEN_COMP_4YR_TRANS_YR2_RT', 'FIRSTGEN_COMP_2YR_TRANS_YR2_RT', 'FIRSTGEN_WDRAW_ORIG_YR2_RT', 'FIRSTGEN_WDRAW_4YR_TRANS_YR2_RT', 'FIRSTGEN_WDRAW_2YR_TRANS_YR2_RT', 'FIRSTGEN_ENRL_ORIG_YR2_RT', 'FIRSTGEN_ENRL_4YR_TRANS_YR2_RT', 'FIRSTGEN_ENRL_2YR_TRANS_YR2_RT', 'FIRSTGEN_UNKN_ORIG_YR2_RT', 'FIRSTGEN_UNKN_4YR_TRANS_YR2_RT', 'FIRSTGEN_UNKN_2YR_TRANS_YR2_RT', 'NOT1STGEN_DEATH_YR2_RT', 'NOT1STGEN_COMP_ORIG_YR2_RT', 'NOT1STGEN_COMP_4YR_TRANS_YR2_RT', 'NOT1STGEN_COMP_2YR_TRANS_YR2_RT', 'NOT1STGEN_WDRAW_ORIG_YR2_RT', 'NOT1STGEN_WDRAW_4YR_TRANS_YR2_RT', 'NOT1STGEN_WDRAW_2YR_TRANS_YR2_RT', 'NOT1STGEN_ENRL_ORIG_YR2_RT', 'NOT1STGEN_ENRL_4YR_TRANS_YR2_RT', 'NOT1STGEN_ENRL_2YR_TRANS_YR2_RT', 'NOT1STGEN_UNKN_ORIG_YR2_RT', 'NOT1STGEN_UNKN_4YR_TRANS_YR2_RT', 'NOT1STGEN_UNKN_2YR_TRANS_YR2_RT', 'DEATH_YR3_RT', 'COMP_ORIG_YR3_RT', 'COMP_4YR_TRANS_YR3_RT', 'COMP_2YR_TRANS_YR3_RT', 'WDRAW_ORIG_YR3_RT', 'WDRAW_4YR_TRANS_YR3_RT', 'WDRAW_2YR_TRANS_YR3_RT', 'ENRL_ORIG_YR3_RT', 'ENRL_4YR_TRANS_YR3_RT', 'ENRL_2YR_TRANS_YR3_RT', 'UNKN_ORIG_YR3_RT', 'UNKN_4YR_TRANS_YR3_RT', 'UNKN_2YR_TRANS_YR3_RT', 'LO_INC_DEATH_YR3_RT', 'LO_INC_COMP_ORIG_YR3_RT', 'LO_INC_COMP_4YR_TRANS_YR3_RT', 'LO_INC_COMP_2YR_TRANS_YR3_RT', 'LO_INC_WDRAW_ORIG_YR3_RT', 'LO_INC_WDRAW_4YR_TRANS_YR3_RT', 'LO_INC_WDRAW_2YR_TRANS_YR3_RT', 'LO_INC_ENRL_ORIG_YR3_RT', 'LO_INC_ENRL_4YR_TRANS_YR3_RT', 'LO_INC_ENRL_2YR_TRANS_YR3_RT', 'LO_INC_UNKN_ORIG_YR3_RT', 'LO_INC_UNKN_4YR_TRANS_YR3_RT', 'LO_INC_UNKN_2YR_TRANS_YR3_RT', 'MD_INC_DEATH_YR3_RT', 'MD_INC_COMP_ORIG_YR3_RT', 'MD_INC_COMP_4YR_TRANS_YR3_RT', 'MD_INC_COMP_2YR_TRANS_YR3_RT', 'MD_INC_WDRAW_ORIG_YR3_RT', 'MD_INC_WDRAW_4YR_TRANS_YR3_RT', 'MD_INC_WDRAW_2YR_TRANS_YR3_RT', 'MD_INC_ENRL_ORIG_YR3_RT', 'MD_INC_ENRL_4YR_TRANS_YR3_RT', 'MD_INC_ENRL_2YR_TRANS_YR3_RT', 'MD_INC_UNKN_ORIG_YR3_RT', 'MD_INC_UNKN_4YR_TRANS_YR3_RT', 'MD_INC_UNKN_2YR_TRANS_YR3_RT', 'HI_INC_DEATH_YR3_RT', 'HI_INC_COMP_ORIG_YR3_RT', 'HI_INC_COMP_4YR_TRANS_YR3_RT', 'HI_INC_COMP_2YR_TRANS_YR3_RT', 'HI_INC_WDRAW_ORIG_YR3_RT', 'HI_INC_WDRAW_4YR_TRANS_YR3_RT', 'HI_INC_WDRAW_2YR_TRANS_YR3_RT', 'HI_INC_ENRL_ORIG_YR3_RT', 'HI_INC_ENRL_4YR_TRANS_YR3_RT', 'HI_INC_ENRL_2YR_TRANS_YR3_RT', 'HI_INC_UNKN_ORIG_YR3_RT', 'HI_INC_UNKN_4YR_TRANS_YR3_RT', 'HI_INC_UNKN_2YR_TRANS_YR3_RT', 'DEP_DEATH_YR3_RT', 'DEP_COMP_ORIG_YR3_RT', 'DEP_COMP_4YR_TRANS_YR3_RT', 'DEP_COMP_2YR_TRANS_YR3_RT', 'DEP_WDRAW_ORIG_YR3_RT', 'DEP_WDRAW_4YR_TRANS_YR3_RT', 'DEP_WDRAW_2YR_TRANS_YR3_RT', 'DEP_ENRL_ORIG_YR3_RT', 'DEP_ENRL_4YR_TRANS_YR3_RT', 'DEP_ENRL_2YR_TRANS_YR3_RT', 'DEP_UNKN_ORIG_YR3_RT', 'DEP_UNKN_4YR_TRANS_YR3_RT', 'DEP_UNKN_2YR_TRANS_YR3_RT', 'IND_DEATH_YR3_RT', 'IND_COMP_ORIG_YR3_RT', 'IND_COMP_4YR_TRANS_YR3_RT', 'IND_COMP_2YR_TRANS_YR3_RT', 'IND_WDRAW_ORIG_YR3_RT', 'IND_WDRAW_4YR_TRANS_YR3_RT', 'IND_WDRAW_2YR_TRANS_YR3_RT', 'IND_ENRL_ORIG_YR3_RT', 'IND_ENRL_4YR_TRANS_YR3_RT', 'IND_ENRL_2YR_TRANS_YR3_RT', 'IND_UNKN_ORIG_YR3_RT', 'IND_UNKN_4YR_TRANS_YR3_RT', 'IND_UNKN_2YR_TRANS_YR3_RT', 'FEMALE_DEATH_YR3_RT', 'FEMALE_COMP_ORIG_YR3_RT', 'FEMALE_COMP_4YR_TRANS_YR3_RT', 'FEMALE_COMP_2YR_TRANS_YR3_RT', 'FEMALE_WDRAW_ORIG_YR3_RT', 'FEMALE_WDRAW_4YR_TRANS_YR3_RT', 'FEMALE_WDRAW_2YR_TRANS_YR3_RT', 'FEMALE_ENRL_ORIG_YR3_RT', 'FEMALE_ENRL_4YR_TRANS_YR3_RT', 'FEMALE_ENRL_2YR_TRANS_YR3_RT', 'FEMALE_UNKN_ORIG_YR3_RT', 'FEMALE_UNKN_4YR_TRANS_YR3_RT', 'FEMALE_UNKN_2YR_TRANS_YR3_RT', 'MALE_DEATH_YR3_RT', 'MALE_COMP_ORIG_YR3_RT', 'MALE_COMP_4YR_TRANS_YR3_RT', 'MALE_COMP_2YR_TRANS_YR3_RT', 'MALE_WDRAW_ORIG_YR3_RT', 'MALE_WDRAW_4YR_TRANS_YR3_RT', 'MALE_WDRAW_2YR_TRANS_YR3_RT', 'MALE_ENRL_ORIG_YR3_RT', 'MALE_ENRL_4YR_TRANS_YR3_RT', 'MALE_ENRL_2YR_TRANS_YR3_RT', 'MALE_UNKN_ORIG_YR3_RT', 'MALE_UNKN_4YR_TRANS_YR3_RT', 'MALE_UNKN_2YR_TRANS_YR3_RT', 'PELL_DEATH_YR3_RT', 'PELL_COMP_ORIG_YR3_RT', 'PELL_COMP_4YR_TRANS_YR3_RT', 'PELL_COMP_2YR_TRANS_YR3_RT', 'PELL_WDRAW_ORIG_YR3_RT', 'PELL_WDRAW_4YR_TRANS_YR3_RT', 'PELL_WDRAW_2YR_TRANS_YR3_RT', 'PELL_ENRL_ORIG_YR3_RT', 'PELL_ENRL_4YR_TRANS_YR3_RT', 'PELL_ENRL_2YR_TRANS_YR3_RT', 'PELL_UNKN_ORIG_YR3_RT', 'PELL_UNKN_4YR_TRANS_YR3_RT', 'PELL_UNKN_2YR_TRANS_YR3_RT', 'NOPELL_DEATH_YR3_RT', 'NOPELL_COMP_ORIG_YR3_RT', 'NOPELL_COMP_4YR_TRANS_YR3_RT', 'NOPELL_COMP_2YR_TRANS_YR3_RT', 'NOPELL_WDRAW_ORIG_YR3_RT', 'NOPELL_WDRAW_4YR_TRANS_YR3_RT', 'NOPELL_WDRAW_2YR_TRANS_YR3_RT', 'NOPELL_ENRL_ORIG_YR3_RT', 'NOPELL_ENRL_4YR_TRANS_YR3_RT', 'NOPELL_ENRL_2YR_TRANS_YR3_RT', 'NOPELL_UNKN_ORIG_YR3_RT', 'NOPELL_UNKN_4YR_TRANS_YR3_RT', 'NOPELL_UNKN_2YR_TRANS_YR3_RT', 'LOAN_DEATH_YR3_RT', 'LOAN_COMP_ORIG_YR3_RT', 'LOAN_COMP_4YR_TRANS_YR3_RT', 'LOAN_COMP_2YR_TRANS_YR3_RT', 'LOAN_WDRAW_ORIG_YR3_RT', 'LOAN_WDRAW_4YR_TRANS_YR3_RT', 'LOAN_WDRAW_2YR_TRANS_YR3_RT', 'LOAN_ENRL_ORIG_YR3_RT', 'LOAN_ENRL_4YR_TRANS_YR3_RT', 'LOAN_ENRL_2YR_TRANS_YR3_RT', 'LOAN_UNKN_ORIG_YR3_RT', 'LOAN_UNKN_4YR_TRANS_YR3_RT', 'LOAN_UNKN_2YR_TRANS_YR3_RT', 'NOLOAN_DEATH_YR3_RT', 'NOLOAN_COMP_ORIG_YR3_RT', 'NOLOAN_COMP_4YR_TRANS_YR3_RT', 'NOLOAN_COMP_2YR_TRANS_YR3_RT', 'NOLOAN_WDRAW_ORIG_YR3_RT', 'NOLOAN_WDRAW_4YR_TRANS_YR3_RT', 'NOLOAN_WDRAW_2YR_TRANS_YR3_RT', 'NOLOAN_ENRL_ORIG_YR3_RT', 'NOLOAN_ENRL_4YR_TRANS_YR3_RT', 'NOLOAN_ENRL_2YR_TRANS_YR3_RT', 'NOLOAN_UNKN_ORIG_YR3_RT', 'NOLOAN_UNKN_4YR_TRANS_YR3_RT', 'NOLOAN_UNKN_2YR_TRANS_YR3_RT', 'FIRSTGEN_DEATH_YR3_RT', 'FIRSTGEN_COMP_ORIG_YR3_RT', 'FIRSTGEN_COMP_4YR_TRANS_YR3_RT', 'FIRSTGEN_COMP_2YR_TRANS_YR3_RT', 'FIRSTGEN_WDRAW_ORIG_YR3_RT', 'FIRSTGEN_WDRAW_4YR_TRANS_YR3_RT', 'FIRSTGEN_WDRAW_2YR_TRANS_YR3_RT', 'FIRSTGEN_ENRL_ORIG_YR3_RT', 'FIRSTGEN_ENRL_4YR_TRANS_YR3_RT', 'FIRSTGEN_ENRL_2YR_TRANS_YR3_RT', 'FIRSTGEN_UNKN_ORIG_YR3_RT', 'FIRSTGEN_UNKN_4YR_TRANS_YR3_RT', 'FIRSTGEN_UNKN_2YR_TRANS_YR3_RT', 'NOT1STGEN_DEATH_YR3_RT', 'NOT1STGEN_COMP_ORIG_YR3_RT', 'NOT1STGEN_COMP_4YR_TRANS_YR3_RT', 'NOT1STGEN_COMP_2YR_TRANS_YR3_RT', 'NOT1STGEN_WDRAW_ORIG_YR3_RT', 'NOT1STGEN_WDRAW_4YR_TRANS_YR3_RT', 'NOT1STGEN_WDRAW_2YR_TRANS_YR3_RT', 'NOT1STGEN_ENRL_ORIG_YR3_RT', 'NOT1STGEN_ENRL_4YR_TRANS_YR3_RT', 'NOT1STGEN_ENRL_2YR_TRANS_YR3_RT', 'NOT1STGEN_UNKN_ORIG_YR3_RT', 'NOT1STGEN_UNKN_4YR_TRANS_YR3_RT', 'NOT1STGEN_UNKN_2YR_TRANS_YR3_RT', 'DEATH_YR4_RT', 'COMP_ORIG_YR4_RT', 'COMP_4YR_TRANS_YR4_RT', 'COMP_2YR_TRANS_YR4_RT', 'WDRAW_ORIG_YR4_RT', 'WDRAW_4YR_TRANS_YR4_RT', 'WDRAW_2YR_TRANS_YR4_RT', 'ENRL_ORIG_YR4_RT', 'ENRL_4YR_TRANS_YR4_RT', 'ENRL_2YR_TRANS_YR4_RT', 'UNKN_ORIG_YR4_RT', 'UNKN_4YR_TRANS_YR4_RT', 'UNKN_2YR_TRANS_YR4_RT', 'LO_INC_DEATH_YR4_RT', 'LO_INC_COMP_ORIG_YR4_RT', 'LO_INC_COMP_4YR_TRANS_YR4_RT', 'LO_INC_COMP_2YR_TRANS_YR4_RT', 'LO_INC_WDRAW_ORIG_YR4_RT', 'LO_INC_WDRAW_4YR_TRANS_YR4_RT', 'LO_INC_WDRAW_2YR_TRANS_YR4_RT', 'LO_INC_ENRL_ORIG_YR4_RT', 'LO_INC_ENRL_4YR_TRANS_YR4_RT', 'LO_INC_ENRL_2YR_TRANS_YR4_RT', 'LO_INC_UNKN_ORIG_YR4_RT', 'LO_INC_UNKN_4YR_TRANS_YR4_RT', 'LO_INC_UNKN_2YR_TRANS_YR4_RT', 'MD_INC_DEATH_YR4_RT', 'MD_INC_COMP_ORIG_YR4_RT', 'MD_INC_COMP_4YR_TRANS_YR4_RT', 'MD_INC_COMP_2YR_TRANS_YR4_RT', 'MD_INC_WDRAW_ORIG_YR4_RT', 'MD_INC_WDRAW_4YR_TRANS_YR4_RT', 'MD_INC_WDRAW_2YR_TRANS_YR4_RT', 'MD_INC_ENRL_ORIG_YR4_RT', 'MD_INC_ENRL_4YR_TRANS_YR4_RT', 'MD_INC_ENRL_2YR_TRANS_YR4_RT', 'MD_INC_UNKN_ORIG_YR4_RT', 'MD_INC_UNKN_4YR_TRANS_YR4_RT', 'MD_INC_UNKN_2YR_TRANS_YR4_RT', 'HI_INC_DEATH_YR4_RT', 'HI_INC_COMP_ORIG_YR4_RT', 'HI_INC_COMP_4YR_TRANS_YR4_RT', 'HI_INC_COMP_2YR_TRANS_YR4_RT', 'HI_INC_WDRAW_ORIG_YR4_RT', 'HI_INC_WDRAW_4YR_TRANS_YR4_RT', 'HI_INC_WDRAW_2YR_TRANS_YR4_RT', 'HI_INC_ENRL_ORIG_YR4_RT', 'HI_INC_ENRL_4YR_TRANS_YR4_RT', 'HI_INC_ENRL_2YR_TRANS_YR4_RT', 'HI_INC_UNKN_ORIG_YR4_RT', 'HI_INC_UNKN_4YR_TRANS_YR4_RT', 'HI_INC_UNKN_2YR_TRANS_YR4_RT', 'DEP_DEATH_YR4_RT', 'DEP_COMP_ORIG_YR4_RT', 'DEP_COMP_4YR_TRANS_YR4_RT', 'DEP_COMP_2YR_TRANS_YR4_RT', 'DEP_WDRAW_ORIG_YR4_RT', 'DEP_WDRAW_4YR_TRANS_YR4_RT', 'DEP_WDRAW_2YR_TRANS_YR4_RT', 'DEP_ENRL_ORIG_YR4_RT', 'DEP_ENRL_4YR_TRANS_YR4_RT', 'DEP_ENRL_2YR_TRANS_YR4_RT', 'DEP_UNKN_ORIG_YR4_RT', 'DEP_UNKN_4YR_TRANS_YR4_RT', 'DEP_UNKN_2YR_TRANS_YR4_RT', 'IND_DEATH_YR4_RT', 'IND_COMP_ORIG_YR4_RT', 'IND_COMP_4YR_TRANS_YR4_RT', 'IND_COMP_2YR_TRANS_YR4_RT', 'IND_WDRAW_ORIG_YR4_RT', 'IND_WDRAW_4YR_TRANS_YR4_RT', 'IND_WDRAW_2YR_TRANS_YR4_RT', 'IND_ENRL_ORIG_YR4_RT', 'IND_ENRL_4YR_TRANS_YR4_RT', 'IND_ENRL_2YR_TRANS_YR4_RT', 'IND_UNKN_ORIG_YR4_RT', 'IND_UNKN_4YR_TRANS_YR4_RT', 'IND_UNKN_2YR_TRANS_YR4_RT', 'FEMALE_DEATH_YR4_RT', 'FEMALE_COMP_ORIG_YR4_RT', 'FEMALE_COMP_4YR_TRANS_YR4_RT', 'FEMALE_COMP_2YR_TRANS_YR4_RT', 'FEMALE_WDRAW_ORIG_YR4_RT', 'FEMALE_WDRAW_4YR_TRANS_YR4_RT', 'FEMALE_WDRAW_2YR_TRANS_YR4_RT', 'FEMALE_ENRL_ORIG_YR4_RT', 'FEMALE_ENRL_4YR_TRANS_YR4_RT', 'FEMALE_ENRL_2YR_TRANS_YR4_RT', 'FEMALE_UNKN_ORIG_YR4_RT', 'FEMALE_UNKN_4YR_TRANS_YR4_RT', 'FEMALE_UNKN_2YR_TRANS_YR4_RT', 'MALE_DEATH_YR4_RT', 'MALE_COMP_ORIG_YR4_RT', 'MALE_COMP_4YR_TRANS_YR4_RT', 'MALE_COMP_2YR_TRANS_YR4_RT', 'MALE_WDRAW_ORIG_YR4_RT', 'MALE_WDRAW_4YR_TRANS_YR4_RT', 'MALE_WDRAW_2YR_TRANS_YR4_RT', 'MALE_ENRL_ORIG_YR4_RT', 'MALE_ENRL_4YR_TRANS_YR4_RT', 'MALE_ENRL_2YR_TRANS_YR4_RT', 'MALE_UNKN_ORIG_YR4_RT', 'MALE_UNKN_4YR_TRANS_YR4_RT', 'MALE_UNKN_2YR_TRANS_YR4_RT', 'PELL_DEATH_YR4_RT', 'PELL_COMP_ORIG_YR4_RT', 'PELL_COMP_4YR_TRANS_YR4_RT', 'PELL_COMP_2YR_TRANS_YR4_RT', 'PELL_WDRAW_ORIG_YR4_RT', 'PELL_WDRAW_4YR_TRANS_YR4_RT', 'PELL_WDRAW_2YR_TRANS_YR4_RT', 'PELL_ENRL_ORIG_YR4_RT', 'PELL_ENRL_4YR_TRANS_YR4_RT', 'PELL_ENRL_2YR_TRANS_YR4_RT', 'PELL_UNKN_ORIG_YR4_RT', 'PELL_UNKN_4YR_TRANS_YR4_RT', 'PELL_UNKN_2YR_TRANS_YR4_RT', 'NOPELL_DEATH_YR4_RT', 'NOPELL_COMP_ORIG_YR4_RT', 'NOPELL_COMP_4YR_TRANS_YR4_RT', 'NOPELL_COMP_2YR_TRANS_YR4_RT', 'NOPELL_WDRAW_ORIG_YR4_RT', 'NOPELL_WDRAW_4YR_TRANS_YR4_RT', 'NOPELL_WDRAW_2YR_TRANS_YR4_RT', 'NOPELL_ENRL_ORIG_YR4_RT', 'NOPELL_ENRL_4YR_TRANS_YR4_RT', 'NOPELL_ENRL_2YR_TRANS_YR4_RT', 'NOPELL_UNKN_ORIG_YR4_RT', 'NOPELL_UNKN_4YR_TRANS_YR4_RT', 'NOPELL_UNKN_2YR_TRANS_YR4_RT', 'LOAN_DEATH_YR4_RT', 'LOAN_COMP_ORIG_YR4_RT', 'LOAN_COMP_4YR_TRANS_YR4_RT', 'LOAN_COMP_2YR_TRANS_YR4_RT', 'LOAN_WDRAW_ORIG_YR4_RT', 'LOAN_WDRAW_4YR_TRANS_YR4_RT', 'LOAN_WDRAW_2YR_TRANS_YR4_RT', 'LOAN_ENRL_ORIG_YR4_RT', 'LOAN_ENRL_4YR_TRANS_YR4_RT', 'LOAN_ENRL_2YR_TRANS_YR4_RT', 'LOAN_UNKN_ORIG_YR4_RT', 'LOAN_UNKN_4YR_TRANS_YR4_RT', 'LOAN_UNKN_2YR_TRANS_YR4_RT', 'NOLOAN_DEATH_YR4_RT', 'NOLOAN_COMP_ORIG_YR4_RT', 'NOLOAN_COMP_4YR_TRANS_YR4_RT', 'NOLOAN_COMP_2YR_TRANS_YR4_RT', 'NOLOAN_WDRAW_ORIG_YR4_RT', 'NOLOAN_WDRAW_4YR_TRANS_YR4_RT', 'NOLOAN_WDRAW_2YR_TRANS_YR4_RT', 'NOLOAN_ENRL_ORIG_YR4_RT', 'NOLOAN_ENRL_4YR_TRANS_YR4_RT', 'NOLOAN_ENRL_2YR_TRANS_YR4_RT', 'NOLOAN_UNKN_ORIG_YR4_RT', 'NOLOAN_UNKN_4YR_TRANS_YR4_RT', 'NOLOAN_UNKN_2YR_TRANS_YR4_RT', 'FIRSTGEN_DEATH_YR4_RT', 'FIRSTGEN_COMP_ORIG_YR4_RT', 'FIRSTGEN_COMP_4YR_TRANS_YR4_RT', 'FIRSTGEN_COMP_2YR_TRANS_YR4_RT', 'FIRSTGEN_WDRAW_ORIG_YR4_RT', 'FIRSTGEN_WDRAW_4YR_TRANS_YR4_RT', 'FIRSTGEN_WDRAW_2YR_TRANS_YR4_RT', 'FIRSTGEN_ENRL_ORIG_YR4_RT', 'FIRSTGEN_ENRL_4YR_TRANS_YR4_RT', 'FIRSTGEN_ENRL_2YR_TRANS_YR4_RT', 'FIRSTGEN_UNKN_ORIG_YR4_RT', 'FIRSTGEN_UNKN_4YR_TRANS_YR4_RT', 'FIRSTGEN_UNKN_2YR_TRANS_YR4_RT', 'NOT1STGEN_DEATH_YR4_RT', 'NOT1STGEN_COMP_ORIG_YR4_RT', 'NOT1STGEN_COMP_4YR_TRANS_YR4_RT', 'NOT1STGEN_COMP_2YR_TRANS_YR4_RT', 'NOT1STGEN_WDRAW_ORIG_YR4_RT', 'NOT1STGEN_WDRAW_4YR_TRANS_YR4_RT', 'NOT1STGEN_WDRAW_2YR_TRANS_YR4_RT', 'NOT1STGEN_ENRL_ORIG_YR4_RT', 'NOT1STGEN_ENRL_4YR_TRANS_YR4_RT', 'NOT1STGEN_ENRL_2YR_TRANS_YR4_RT', 'NOT1STGEN_UNKN_ORIG_YR4_RT', 'NOT1STGEN_UNKN_4YR_TRANS_YR4_RT', 'NOT1STGEN_UNKN_2YR_TRANS_YR4_RT', 'INC_PCT_LO', 'DEP_STAT_PCT_IND', 'DEP_INC_PCT_LO', 'IND_INC_PCT_LO', 'PAR_ED_PCT_1STGEN', 'INC_PCT_M1', 'INC_PCT_M2', 'INC_PCT_H1', 'INC_PCT_H2', 'DEP_INC_PCT_M1', 'DEP_INC_PCT_M2', 'DEP_INC_PCT_H1', 'DEP_INC_PCT_H2', 'IND_INC_PCT_M1', 'IND_INC_PCT_M2', 'IND_INC_PCT_H1', 'IND_INC_PCT_H2', 'PAR_ED_PCT_MS', 'PAR_ED_PCT_HS', 'PAR_ED_PCT_PS', 'APPL_SCH_PCT_GE2', 'APPL_SCH_PCT_GE3', 'APPL_SCH_PCT_GE4', 'APPL_SCH_PCT_GE5', 'DEP_INC_AVG', 'IND_INC_AVG', 'OVERALL_YR2_N', 'LO_INC_YR2_N', 'MD_INC_YR2_N', 'HI_INC_YR2_N', 'DEP_YR2_N', 'IND_YR2_N', 'FEMALE_YR2_N', 'MALE_YR2_N', 'PELL_YR2_N', 'NOPELL_YR2_N', 'LOAN_YR2_N', 'NOLOAN_YR2_N', 'FIRSTGEN_YR2_N', 'NOT1STGEN_YR2_N', 'OVERALL_YR3_N', 'LO_INC_YR3_N', 'MD_INC_YR3_N', 'HI_INC_YR3_N', 'DEP_YR3_N', 'IND_YR3_N', 'FEMALE_YR3_N', 'MALE_YR3_N', 'PELL_YR3_N', 'NOPELL_YR3_N', 'LOAN_YR3_N', 'NOLOAN_YR3_N', 'FIRSTGEN_YR3_N', 'NOT1STGEN_YR3_N', 'OVERALL_YR4_N', 'LO_INC_YR4_N', 'MD_INC_YR4_N', 'HI_INC_YR4_N', 'DEP_YR4_N', 'IND_YR4_N', 'FEMALE_YR4_N', 'MALE_YR4_N', 'PELL_YR4_N', 'NOPELL_YR4_N', 'LOAN_YR4_N', 'NOLOAN_YR4_N', 'FIRSTGEN_YR4_N', 'NOT1STGEN_YR4_N', 'DEBT_MDN', 'GRAD_DEBT_MDN', 'WDRAW_DEBT_MDN', 'LO_INC_DEBT_MDN', 'MD_INC_DEBT_MDN', 'HI_INC_DEBT_MDN', 'DEP_DEBT_MDN', 'IND_DEBT_MDN', 'PELL_DEBT_MDN', 'NOPELL_DEBT_MDN', 'FEMALE_DEBT_MDN', 'MALE_DEBT_MDN', 'FIRSTGEN_DEBT_MDN', 'NOTFIRSTGEN_DEBT_MDN', 'DEBT_N', 'GRAD_DEBT_N', 'WDRAW_DEBT_N', 'LO_INC_DEBT_N', 'MD_INC_DEBT_N', 'HI_INC_DEBT_N', 'DEP_DEBT_N', 'IND_DEBT_N', 'PELL_DEBT_N', 'NOPELL_DEBT_N', 'FEMALE_DEBT_N', 'MALE_DEBT_N', 'FIRSTGEN_DEBT_N', 'NOTFIRSTGEN_DEBT_N', 'CUML_DEBT_N', 'CUML_DEBT_P90', 'CUML_DEBT_P75', 'CUML_DEBT_P25', 'CUML_DEBT_P10', 'INC_N', 'DEP_INC_N', 'IND_INC_N', 'DEP_STAT_N', 'PAR_ED_N', 'APPL_SCH_N', 'REPAY_DT_N', 'SEPAR_DT_N', 'LOAN_EVER', 'PELL_EVER', 'AGE_ENTRY', 'FEMALE', 'MARRIED', 'DEPENDENT', 'VETERAN', 'FIRST_GEN', 'FAMINC', 'MD_FAMINC', 'FAMINC_IND', 'MD_EARN_WNE_P10', 'DEBT_MDN_SUPP', 'GRAD_DEBT_MDN_SUPP']
for i in range(len(cleaned_data)):
    for key in list(cleaned_data[i].keys()):
        if key not in numerical:
            cleaned_data[i].pop(key)
cdi = get_data_info(cleaned_data)
print(len(cdi['headers']))

# Get mean value for each column
cdi['headers_mean'] = dict()
for header in cdi['headers']:
    temp = list()
    for line in cleaned_data:
        if header in line:
            temp.append(line[header])
    cdi['headers_mean'][header] = sum(temp)/len(temp)

# Fill Null values with mean
for i in range(len(cleaned_data)):
    for header in cdi['headers']:
        if header not in cleaned_data[i]:
            cleaned_data[i][header] = cdi['headers_mean'][header]
cdi = get_data_info(cleaned_data)
pprint(list(header for header in cdi['headers_null_size'] if cdi['headers_null_size'][header] != 0))

# Write data to csv file
with open('/home/windr/CS593_Data/test.csv', 'w') as fh:
    headers = tuple(cdi['headers'].keys())
    fh.write(','.join(headers) + '\n')
    for line in cleaned_data:
        fh.write(','.join(tuple(str(line[head]) for head in headers)) + '\n')
